# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import json
from pathlib import Path

from core import machine_sheet

_CACHY_OS_RELEASE = """\
NAME="CachyOS"
PRETTY_NAME="CachyOS"
ID=cachyos
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://discuss.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos
"""

_MINT_OS_RELEASE = """\
NAME="Linux Mint"
VERSION="22.1 Xia"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22.1"
VERSION_ID="22.1"
HOME_URL="https://www.linuxmint.com/"
VERSION_CODENAME=xia
UBUNTU_CODENAME=noble
"""

_MEMINFO = """\
MemTotal:       32802432 kB
MemFree:         4123456 kB
MemAvailable:   21456780 kB
Buffers:          512000 kB
Cached:         16000000 kB
SwapTotal:       8388608 kB
SwapFree:        8388608 kB
"""

_DF_P = """\
Filesystem     1024-blocks      Used Available Capacity Mounted on
/dev/nvme0n1p2   479711192  86000000 369000000      19% /
tmpfs             16401216       128  16401088       1% /tmp
devtmpfs             4096         0      4096       0% /dev
overlay          479711192  86000000 369000000      19% /var/lib/docker/overlay2
/dev/nvme0n1p2   479711192  86000000 369000000      19% /root
/dev/nvme0n1p2   479711192  86000000 369000000      19% /var/log
none                 65536         0     65536       0% /dev/shm
/dev/nvme0n1p3   104857600  42000000  58000000      42% /home
/dev/sda1         30720000   4100000  25000000      15% /mnt/data
squashfs            120000    120000         0     100% /snap/core/1
"""

_DF_P_FR = """\
Sys. de fichiers 1024-blocs  Utilisé Disponible Capacité Monté sur
/dev/nvme0n1p5    418575360 87415140  327719772      22% /
/dev/nvme0n1p5    418575360 87415140  327719772      22% /home
/dev/nvme0n1p6      3065992   524684    2541308      18% /boot
"""

_IP_ROUTE = """\
[{"dst":"default","gateway":"192.168.1.1","dev":"enp2s0","protocol":"dhcp"},{"dst":"192.168.1.0/24","dev":"enp2s0"}]
"""

_CPUINFO = """\
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 97
model name	: AMD Ryzen 7 7800X3D 8-Core Processor
physical id	: 0
core id		: 0
processor	: 1
model name	: AMD Ryzen 7 7800X3D 8-Core Processor
physical id	: 0
core id		: 1
processor	: 2
model name	: AMD Ryzen 7 7800X3D 8-Core Processor
physical id	: 0
core id		: 2
"""

_RESOLV = """\
# Generated by NetworkManager
nameserver 1.1.1.1
nameserver 9.9.9.9
nameserver 1.1.1.1
search lan
"""

_PROC_ROUTE = """\
Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
enp2s0	00000000	0100A8C0	0003	0	0	100	00000000	0	0	0
enp2s0	0000A8C0	00000000	0001	0	0	100	00FFFFFF	0	0	0
"""

_PACMAN_QU = """\
linux 6.12.1-1 -> 6.12.2-1
firefox 130.0-1 -> 131.0-1
"""

_APT_UPGRADABLE = """\
Listing...
base-files/noble-updates 13ubuntu10.2 amd64 [upgradable from: 13ubuntu10.1]
bash/noble-updates 5.2.21-2ubuntu4 amd64 [upgradable from: 5.2.21-2ubuntu3]
"""


def test_parse_os_release_cachy_and_mint() -> None:
    cachy = machine_sheet.parse_os_release(_CACHY_OS_RELEASE)
    assert cachy["ID"] == "cachyos"
    assert cachy["PRETTY_NAME"] == "CachyOS"
    assert cachy["ID_LIKE"] == "arch"
    mint = machine_sheet.parse_os_release(_MINT_OS_RELEASE)
    assert mint["ID"] == "linuxmint"
    assert mint["PRETTY_NAME"] == "Linux Mint 22.1"
    assert mint["VERSION_ID"] == "22.1"


def test_parse_os_release_skips_comments_and_blank() -> None:
    data = machine_sheet.parse_os_release("# comment\n\nID=arch\n")
    assert data == {"ID": "arch"}


def test_parse_meminfo_kib_to_bytes() -> None:
    mem = machine_sheet.parse_meminfo(_MEMINFO)
    assert mem["MemTotal"] == 32802432 * 1024
    assert mem["MemAvailable"] == 21456780 * 1024
    assert mem["SwapTotal"] == 8388608 * 1024
    ram = machine_sheet.ram_from_meminfo(mem)
    assert ram["total_gib"] == round(32802432 / 1024 / 1024, 2)
    used = 32802432 - 21456780
    assert ram["used_gib"] == round(used / 1024 / 1024, 2)
    assert ram["percent"] == round((used / 32802432) * 100, 1)


def test_parse_df_p_keeps_useful_mounts() -> None:
    mounts = machine_sheet.parse_df_p(_DF_P)
    points = [row["mountpoint"] for row in mounts]
    assert "/" in points
    assert "/home" in points
    assert "/mnt/data" in points
    assert "/tmp" not in points
    assert "/dev" not in points
    assert "/root" not in points
    assert "/var/log" not in points
    assert "/dev/shm" not in points
    assert "/var/lib/docker/overlay2" not in points
    assert "/snap/core/1" not in points
    root = next(row for row in mounts if row["mountpoint"] == "/")
    assert root["percent"] == 19.0
    assert root["fstype"] == ""
    assert root["device"] == "/dev/nvme0n1p2"
    assert root["total_kib"] == 479711192
    assert root["used_kib"] == 86000000
    assert root["avail_kib"] == 369000000


def test_parse_df_p_french_header_and_boot() -> None:
    mounts = machine_sheet.parse_df_p(_DF_P_FR)
    points = [row["mountpoint"] for row in mounts]
    assert points == ["/", "/home", "/boot"]


def test_parse_ip_route_json_default() -> None:
    assert machine_sheet.parse_ip_route_json(_IP_ROUTE) == "192.168.1.1"


def test_parse_cpuinfo_model_and_cores() -> None:
    cpu = machine_sheet.parse_cpuinfo(_CPUINFO)
    assert cpu["model"] == "AMD Ryzen 7 7800X3D 8-Core Processor"
    assert cpu["logical_cores"] == 3


def test_parse_resolv_conf_unique_nameservers() -> None:
    assert machine_sheet.parse_resolv_conf(_RESOLV) == ["1.1.1.1", "9.9.9.9"]


def test_parse_proc_route_default_gateway() -> None:
    assert machine_sheet.parse_proc_route(_PROC_ROUTE) == "192.168.0.1"


def test_parse_package_cache_lists() -> None:
    assert machine_sheet.parse_pacman_qu(_PACMAN_QU) == ["linux", "firefox"]
    assert machine_sheet.parse_apt_upgradable(_APT_UPGRADABLE) == ["base-files", "bash"]


def test_assemble_sheet_from_raw_bundle() -> None:
    raw = {
        "os_release": _CACHY_OS_RELEASE,
        "meminfo": _MEMINFO,
        "df": _DF_P,
        "cpuinfo": _CPUINFO,
        "resolv": _RESOLV,
        "route": _PROC_ROUTE,
        "ip_route": _IP_ROUTE,
        "hostname": "atelier-cachy",
        "kernel": "Linux 6.16.1-cachyos",
        "machine": "x86_64",
        "timezone": "Europe/Paris",
        "datetime": "2026-08-18 11:00:00",
        "uptime_s": 3661,
        "gpu": {"available": True, "devices": [{"vendor": "AMD", "name": "Radeon"}]},
            "interfaces": [
                {"name": "enp2s0", "ipv4": ["192.168.0.10"], "ipv6": [], "is_up": True},
                {"name": "lo", "ipv4": ["127.0.0.1"], "ipv6": ["::1"], "is_up": True},
                {"name": "vethdb6fd8e", "ipv4": [], "ipv6": ["fe80::1"], "is_up": True},
                {"name": "docker0", "ipv4": ["172.17.0.1"], "ipv6": [], "is_up": True},
            ],
        "pacman_qu": _PACMAN_QU,
        "apt_upgradable": "",
        "snapshots": {"detected": True, "backend": "snapper"},
    }
    sheet = machine_sheet.assemble_sheet(raw)
    assert sheet["identity"]["hostname"] == "atelier-cachy"
    assert sheet["identity"]["pretty_name"] == "CachyOS"
    assert sheet["identity"]["os_id"] == "cachyos"
    assert sheet["cpu"]["model"].startswith("AMD Ryzen")
    assert sheet["cpu"]["logical_cores"] == 3
    assert sheet["ram"]["total_gib"] > 30
    assert any(m["mountpoint"] == "/" for m in sheet["storage"])
    assert sheet["network"]["gateway"] == "192.168.1.1"
    assert sheet["network"]["dns"] == ["1.1.1.1", "9.9.9.9"]
    names = [item.get("name") for item in sheet["network"]["interfaces"]]
    assert names == ["enp2s0"]
    assert sheet["updates"]["pending"] == 2
    assert sheet["snapshots"]["detected"] is True
    text = machine_sheet.to_text(sheet)
    assert "atelier-cachy" in text
    assert "CachyOS" in text
    payload = json.loads(machine_sheet.to_json(sheet))
    assert payload["identity"]["hostname"] == "atelier-cachy"
    csv_text = machine_sheet.to_csv(sheet)
    assert csv_text.splitlines()[0].startswith("section,key,value")
    assert "identity,hostname,atelier-cachy" in csv_text


def test_collect_inventory_raw_reads_local_proc() -> None:
    from core import host_probe

    raw = host_probe.collect_inventory_raw()
    assert "MemTotal" in raw["meminfo"]
    assert "=" in raw["os_release"]
    sheet = machine_sheet.assemble_sheet(raw)
    assert sheet["identity"]["arch"]
    assert isinstance(sheet["storage"], list)


def test_assemble_sheet_empty_raw_is_safe() -> None:
    sheet = machine_sheet.assemble_sheet({})
    assert sheet["identity"]["hostname"] == ""
    assert sheet["updates"]["pending"] == 0
    assert sheet["snapshots"]["detected"] is False
    assert machine_sheet.to_csv(sheet).startswith("section,key,value")
